---
application:
  db:
    host: localhost
    port: 3306
    name: apiatlashub_db
    user: apiatlashub_user
    password: ApiAtlasHub2024
  oauth2:
    issuer-uri: https://atlashubapi-dev.eu.auth0.com/
    audience: Bankwiz_server
