---
application:
  url: http://localhost:9595
  cors-allowed-origins: ""
  server:
    port: 9595
  db:
    host: dblocalhost
    port: 5432
    name: dbname
    user: dbuser
    password: dbpassword
  oauth2:
    issuer-uri: https://example.com/
    audience: audience
server:
  port: "${application.server.port}"
spring:
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    url: "jdbc:mysql://${application.db.host}:${application.db.port}/${application.db.name}"
    username: "${application.db.user}"
    password: "${application.db.password}"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${application.oauth2.issuer-uri}"
          jwk-set-uri: "${application.oauth2.issuer-uri}.well-known/jwks.json"
